### ISSUE TITLE
AppVeyor binary 1.0.38 does not export data from specified table

### ISSUE THREAD

**Issue by BR-Nicholas-Prado** [PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool#1]
## Steps

. navigated ms cmd.exe to db schema export tool exe directory
. created data filter file with one line "apaaArchitectureTest"
. typed command `DB_Schema_Export_Tool_GUI.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass ffffffff -DB workflo -NoAutoData -MaxRows 0 -Data:"D:\Nicholas\dl\spent\20200118_meta.txt" -TableFilterList:D:\Nicholas\dl\spent\20200118_meta.txt`
. checked output folder

### Expected

* file called apaaArchitectureTest.sql (with definition)
* file called apaaArchitectureTest_Data.sql (with 7 rows)

### Saw

* file called apaaArchitectureTest.sql (with definition)
* 783 unexpected definition files
* _absence_ of apaaArchitectureTest_Data.sql

### Environment
* DB-Schema-Export-Tool version : 1.0.38 (from the AppVeyor site, built 2020 01 18)
OS: Windows 10 Pro x64 v1909 build 18363.592
Db server: Sql Server 2008 standard v10.0.0.1600.22

### Log

```
Options:

 Output directory path:                           D:\Nicholas\dl\spent
 Create directory for each DB:                    Enabled
 Source Server:                                   192.168.1.23
 Server type:                                     Microsoft SQL Server
 Database user:                                   sa
 Password:                                        Provided
 Database to export:                              workflo
 Database Subdirectory Prefix:                    DBSchema__
 Dump table data as:                              INSERT INTO statements
 File with table names for exporting data:        D:\Nicholas\dl\spent\20200118_meta.txt
 Default value for the PgInsert column:           False
 PgInsert chunk size:                             50000
 Single table to process:                         D:\Nicholas\dl\spent\20200118_meta.txt
 Data export from standard tables:                Disabled
 Use snake_case for table and column names:       Disabled
 Maximum rows to export, per table:               0
 Export server settings, logins, and jobs:        Disabled
 Create a bash script for loading data with psql: Enabled
 Base log file name:                              Default

2020-01-18 17:11:33, Exporting schema/data to: D:\Nicholas\dl\spent, INFO
2020-01-18 17:11:33, Connecting to 192.168.1.23, DEBUG
2020-01-18 17:11:33, Exporting DB objects/data to: D:\Nicholas\dl\spent, INFO
2020-01-18 17:11:33, Exporting objects and data from database workflo, DEBUG
2020-01-18 17:11:33, Auto-selecting tables to export data from, DEBUG
2020-01-18 17:11:33, Counting number of objects to export, DEBUG
2020-01-18 17:11:33, Scripting 738 objects, DEBUG
2020-01-18 17:12:25, Processing completed for database workflo, INFO
```

### Alternate Ineffective Steps

* command `DB_Schema_Export_Tool_GUI.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass ffffffff -DB workflo -NoAutoData -MaxRows 0 -NoSchema -Data "D:\Nicholas\dl\spent\20200118_meta.txt" -TableFilterList:D:\Nicholas\dl\spent\20200118_meta.txt -AllData`

#### Saw

* _absence_ of apaaArchitectureTest_Data.sql

```
[...]
Single table to process:                         D:\Nicholas\dl\spent\20200118_meta.txt
 Data export from all tables:                     Enabled
 Use snake_case for table and column names:       Disabled
 Maximum rows to export, per table:               0
 Export table data only; no schema:               Enabled
 Create a bash script for loading data with psql: Disabled

Exporting schema/data to: D:\Nicholas\dl\spent

  Connecting to 192.168.1.23

Exporting DB objects/data to: D:\Nicholas\dl\spent
0.00%: Obtaining list of databases on 192.168.1.23
0.00%: Exporting data from database workflo

  Exporting data from database workflo

  Auto-selecting tables to export data from

  Counting number of objects to export

  Scripting 1 objects

Processing completed for database workflo

Processing complete
```

### Alternate step with preview

* command `DB_Schema_Export_Tool_GUI.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass ffff -DB workflo -NoAutoData -MaxRows 0 -NoSchema -Data "D:\Nicholas\dl\spent\20200118_meta.txt" -TableFilterList:D:\Nicholas\dl\spent\20200118_meta.txt -Preview`

Output

```
Options:

 Output directory path:                           D:\Nicholas\dl\spent
 Create directory for each DB:                    Enabled
 Source Server:                                   192.168.1.23
 Server type:                                     Microsoft SQL Server
 Database user:                                   sa
 Password:                                        Provided
 Database to export:                              workflo
 Database Subdirectory Prefix:                    DBSchema__
 Dump table data as:                              INSERT INTO statements
 File with table names for exporting data:        D:\Nicholas\dl\spent\20200118_meta.txt
 Default value for the PgInsert column:           False
 PgInsert chunk size:                             50000
 Single table to process:                         D:\Nicholas\dl\spent\20200118_meta.txt
 Data export from standard tables:                Disabled
 Use snake_case for table and column names:       Disabled
 Maximum rows to export, per table:               0
 Export table data only; no schema:               Enabled
 Create a bash script for loading data with psql: Disabled
 Preview mode: counting the number of database objects that would be exported

Exporting schema/data to: D:\Nicholas\dl\spent

  Connecting to 192.168.1.23

Exporting DB objects/data to: D:\Nicholas\dl\spent
0.00%: Obtaining list of databases on 192.168.1.23
0.00%: Exporting data from database workflo

  Exporting data from database workflo

  Auto-selecting tables to export data from

  Counting number of objects to export

  Found 0 database objects to export

Processing completed for database workflo

Processing complete
```

### Alternate steps to affirm any export

* command `DB_Schema_Export_Tool_GUI.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass ffffffff -DB workflo -NoAutoData -MaxRows 0 -NoSchema -AllData`

#### Saw

* 783 data files, including apaaArchitectureTest_Data.sql (fewer, actually, because I cancelled, given that I don't need any but one)

### Addendum

I'm not familiar with C#, so I'm not sure how to really diagnose this. I seems like `tablesForDataExport` is empty in `DBSchemaExporterSQLServer.ExportDBObjectsUsingSMO()` on line 344. I don't have a visual studio to trace all this with, so I traced by eye with github. Also, I would expect that, otherwise, the preview run's output would say 'Would export table data for 1 tables', because of `DBSchemaExporterSQLServer.ExportDBObjectsUsingSMO()` line 453. I traced the table list to `DBSchemaExportTool.LoadTablesForDataExport()` line 758+.

It's not clear why the [data file I used](https://github.com/PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool/files/4082105/20200118_meta.txt) wouldn't work, so I've attached it. I've also attached [the zip of the schema](https://github.com/PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool/files/4082106/apaaArchitectureTest.zip) and data output for the table of the same name, to show that I've not misspelt it. (Zip because gh doesn't allow files of extension sql.) I've also tried a version that has the namespace for the table, workflo.dbo.apaaArchitectureTest, with no difference.

Presumably it found something, given that it says either tablesForDataExport or tablesToExportData has 1 value on line 464 of DBSchemaExporterSQLServer.

**Comment by alchemistmatt** [comment]
Thanks for the thoroughness of what you have tried.  So ... it's exporting data from tables, but not from the table you want, correct?  You shouldn't need both `-data` and `-TableFilterList` ; I suggest just sticking with `-data`  Also, I suggest you use a parameter file (configuration file) instead of command line switches.  An example parameter file is at https://github.com/PNNL-Comp-Mass-Spec/DB-Schema-Export-Tool/blob/master/Data/ExportOptions_ManagerControl.conf

Invoke the program with 
```
DB_Schema_Export_Tool_GUI.exe -conf Workflo.conf
```
I will probably need to add some more debug messages to help figure out the issue.  I also should update the Appveyor command to build the console version (in addition to the GUI version); if that's possible.  Both versions use the same code, though, so that's not the issue.

**Comment by alchemistmatt** [comment]
Oh, you want both the schema and the data for that table.  In that case, yes, you would need to use `-TableFilterList`  I likely need to test that further, using similar parameters as you.  I only added `-TableFilterList` within the last week.

**Comment by alchemistmatt** [comment]
As you discovered, by default this program creates .sql files for every table, view, function, and procedure in the database, thus leading to the 783 unexpected files.  As you found, you can use `-NoSchema` to prevent this.

The reason the data is not exporting from table apaaArchitectureTest is that you specified a filepath for 
`-TableFilterList`
That parameter is supposed to be a table name, or a comma separated list of table names; not a file path.  
Since you are specifying tables using the `-Data` switch, you don't need the `-TableFilterList` switch.  

This works:
```
DB_Schema_Export_Tool.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass ffff -DB workflo -NoAutoData -MaxRows 0 -NoSchema -Data "D:\Nicholas\dl\spent\20200118_meta.txt"
```

This also works
```
DB_Schema_Export_Tool.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass ffff -DB workflo -NoAutoData -MaxRows 0 -NoSchema -Data "D:\Nicholas\dl\spent\20200118_meta.txt" -TableFilterList:apaaArchitectureTest
```

Note that I updated the AppVeyor build config to build the console application, `DB_Schema_Export_Tool.exe`

AppVeyor is also building the GUI, in case you need it.  

Finally, I added the optional argument `-Trace`, which shows additional messages.  I have also expanded the Readme a bit more.

**Comment by alchemistmatt** [comment]
Commit 784b5fcfb58330bb01d35aebcfcac535383997a6 implements the feature that when `-TableFilterList` is used, but `-NoSchema` is not used, only the schema for the table (or tables) specified by `-TableFilterList` will be exported.

**Comment by BR-Nicholas-Prado** [comment]
I affirm that artifact 1.0.41, when specifying the table filter list exports the schema and data from the specified tables. This resolves the problematic behavior preventing my use case. Closing this issue; thanks muchly.

command `DB_Schema_Export_Tool_GUI.exe /Server:192.168.1.23 -O D:\Nicholas\dl\spent -DBUser sa -DBPass 0000000 -DB workflo -NoAutoData -MaxRows 0 -Data:"D:\Nicholas\dl\spent\20200118_meta.txt" -TableFilterList:apazBrowserColumn,apaaArchitectureTest`

Output
```
Options:

 Output directory path:                           D:\Nicholas\dl\spent
 Create directory for each DB:                    Enabled
 Source Server:                                   192.168.1.23
 Server type:                                     Microsoft SQL Server
 Database user:                                   sa
 Password:                                        Provided
 Database to export:                              workflo
 Database Subdirectory Prefix:                    DBSchema__
 Dump table data as:                              INSERT INTO statements
 File with table names for exporting data:        D:\Nicholas\dl\spent\20200118_meta.txt
 Default value for the PgInsert column:           False
 PgInsert chunk size:                             50000
 List of tables to process:                       apaaArchitectureTest, apazBrowserColumn
 Data export from standard tables:                Disabled
 Use snake_case for table and column names:       Disabled
 Maximum rows to export, per table:               0
 Export server settings, logins, and jobs:        Disabled
 Create a bash script for loading data with psql: Disabled

Exporting schema/data to: D:\Nicholas\dl\spent

  Connecting to 192.168.1.23

Exporting DB objects/data to: D:\Nicholas\dl\spent
0.00%: Obtaining list of databases on 192.168.1.23
0.00%: Exporting objects and data from database workflo

  Exporting objects and data from database workflo

  Auto-selecting tables for data export in database workflo

  Counting number of objects to export

  Scripting 733 objects
0.55%: Scripting workflo.dbo.apaaArchitectureTest
24.56%: Scripting workflo.dbo.apazBrowserColumn

  Exporting data from database workflo, tables apazBrowserColumn and apaaArchitectureTest
99.73%: Exporting data from apazBrowserColumn

  Writing table data to D:\Nicholas\dl\spent\DBSchema__workflo\apazBrowserColumn_Data.sql
99.86%: Exporting data from apaaArchitectureTest

  Writing table data to D:\Nicholas\dl\spent\DBSchema__workflo\apaaArchitectureTest_Data.sql

Processing completed for database workflo

Processing complete
```
